[target.aarch64-unknown-linux-gnu]
pre-build = [ "apt-get update && apt-get install --assume-yes libfontconfig-dev" ]

[target.x86_64-unknown-linux-gnu]
pre-build = [ "apt-get update && apt-get install --assume-yes libfontconfig-dev" ]
