complete -c switcheroo -n "__fish_use_subcommand" -s v -l verbose -d 'More output per occurrence'
complete -c switcheroo -n "__fish_use_subcommand" -s q -l quiet -d 'Less output per occurrence'
complete -c switcheroo -n "__fish_use_subcommand" -s h -l help -d 'Print help'
complete -c switcheroo -n "__fish_use_subcommand" -s V -l version -d 'Print version'
complete -c switcheroo -n "__fish_use_subcommand" -f -a "execute" -d 'Executes a provided payload'
complete -c switcheroo -n "__fish_use_subcommand" -f -a "device" -d 'Checks if a Switch in RCM mode is detected'
complete -c switcheroo -n "__fish_use_subcommand" -f -a "list" -d 'Lists favorites'
complete -c switcheroo -n "__fish_use_subcommand" -f -a "add" -d 'Add a favorite'
complete -c switcheroo -n "__fish_use_subcommand" -f -a "remove" -d 'Remove a favorite'
complete -c switcheroo -n "__fish_use_subcommand" -f -a "gui" -d 'Opens the Graphical User Interface'
complete -c switcheroo -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c switcheroo -n "__fish_seen_subcommand_from execute" -s f -l favorite -d 'Use a favorite payload'
complete -c switcheroo -n "__fish_seen_subcommand_from execute" -s w -l wait -d 'Wait for device to be connected'
complete -c switcheroo -n "__fish_seen_subcommand_from execute" -s v -l verbose -d 'More output per occurrence'
complete -c switcheroo -n "__fish_seen_subcommand_from execute" -s q -l quiet -d 'Less output per occurrence'
complete -c switcheroo -n "__fish_seen_subcommand_from execute" -s h -l help -d 'Print help'
complete -c switcheroo -n "__fish_seen_subcommand_from device" -s v -l verbose -d 'More output per occurrence'
complete -c switcheroo -n "__fish_seen_subcommand_from device" -s q -l quiet -d 'Less output per occurrence'
complete -c switcheroo -n "__fish_seen_subcommand_from device" -s h -l help -d 'Print help'
complete -c switcheroo -n "__fish_seen_subcommand_from list" -s v -l verbose -d 'More output per occurrence'
complete -c switcheroo -n "__fish_seen_subcommand_from list" -s q -l quiet -d 'Less output per occurrence'
complete -c switcheroo -n "__fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c switcheroo -n "__fish_seen_subcommand_from add" -s v -l verbose -d 'More output per occurrence'
complete -c switcheroo -n "__fish_seen_subcommand_from add" -s q -l quiet -d 'Less output per occurrence'
complete -c switcheroo -n "__fish_seen_subcommand_from add" -s h -l help -d 'Print help'
complete -c switcheroo -n "__fish_seen_subcommand_from remove" -s v -l verbose -d 'More output per occurrence'
complete -c switcheroo -n "__fish_seen_subcommand_from remove" -s q -l quiet -d 'Less output per occurrence'
complete -c switcheroo -n "__fish_seen_subcommand_from remove" -s h -l help -d 'Print help'
complete -c switcheroo -n "__fish_seen_subcommand_from gui" -s v -l verbose -d 'More output per occurrence'
complete -c switcheroo -n "__fish_seen_subcommand_from gui" -s q -l quiet -d 'Less output per occurrence'
complete -c switcheroo -n "__fish_seen_subcommand_from gui" -s h -l help -d 'Print help'
complete -c switcheroo -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from execute; and not __fish_seen_subcommand_from device; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from gui; and not __fish_seen_subcommand_from help" -f -a "execute" -d 'Executes a provided payload'
complete -c switcheroo -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from execute; and not __fish_seen_subcommand_from device; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from gui; and not __fish_seen_subcommand_from help" -f -a "device" -d 'Checks if a Switch in RCM mode is detected'
complete -c switcheroo -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from execute; and not __fish_seen_subcommand_from device; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from gui; and not __fish_seen_subcommand_from help" -f -a "list" -d 'Lists favorites'
complete -c switcheroo -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from execute; and not __fish_seen_subcommand_from device; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from gui; and not __fish_seen_subcommand_from help" -f -a "add" -d 'Add a favorite'
complete -c switcheroo -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from execute; and not __fish_seen_subcommand_from device; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from gui; and not __fish_seen_subcommand_from help" -f -a "remove" -d 'Remove a favorite'
complete -c switcheroo -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from execute; and not __fish_seen_subcommand_from device; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from gui; and not __fish_seen_subcommand_from help" -f -a "gui" -d 'Opens the Graphical User Interface'
complete -c switcheroo -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from execute; and not __fish_seen_subcommand_from device; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from remove; and not __fish_seen_subcommand_from gui; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
