complete -c switcheroo -n "__fish_use_subcommand" -s h -l help -d 'Print help information'
complete -c switcheroo -n "__fish_use_subcommand" -s V -l version -d 'Print version information'
complete -c switcheroo -n "__fish_use_subcommand" -s v -l verbose -d 'Verbosity'
complete -c switcheroo -n "__fish_use_subcommand" -f -a "execute" -d 'Executes a provided payload'
complete -c switcheroo -n "__fish_use_subcommand" -f -a "device" -d 'Checks if a Switch in RCM mode is detected'
complete -c switcheroo -n "__fish_use_subcommand" -f -a "list" -d 'Lists favorites'
complete -c switcheroo -n "__fish_use_subcommand" -f -a "add" -d 'Add a favorite'
complete -c switcheroo -n "__fish_use_subcommand" -f -a "remove" -d 'Remove a favorite'
complete -c switcheroo -n "__fish_use_subcommand" -f -a "gui" -d 'Opens the Graphical User Interface'
complete -c switcheroo -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c switcheroo -n "__fish_seen_subcommand_from execute" -s f -l favorite -d 'Use a favorite payload'
complete -c switcheroo -n "__fish_seen_subcommand_from execute" -s w -l wait -d 'Wait for device to be connected'
complete -c switcheroo -n "__fish_seen_subcommand_from execute" -s h -l help -d 'Print help information'
complete -c switcheroo -n "__fish_seen_subcommand_from device" -s h -l help -d 'Print help information'
complete -c switcheroo -n "__fish_seen_subcommand_from list" -s h -l help -d 'Print help information'
complete -c switcheroo -n "__fish_seen_subcommand_from add" -s h -l help -d 'Print help information'
complete -c switcheroo -n "__fish_seen_subcommand_from remove" -s h -l help -d 'Print help information'
complete -c switcheroo -n "__fish_seen_subcommand_from gui" -s h -l help -d 'Print help information'
